name: Build DMediatR.nupkg

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Build DMediatR
    - name: Restore dependencies
      run: dotnet restore DMediatR.sln
    - name: Build the solution
      run: dotnet build DMediatR.sln --configuration=Release
    
      # Exclude integration tests as github workflows are prohibited to start DMediatRNode processes:
    - name: Test the solution
      run: dotnet test DMediatR.sln --configuration=Release --no-build --verbosity normal -- NUnit.Where="cat != Integration"
      
    - name: Create .nupkg packages
      run: dotnet pack DMediatR.sln --configuration Release --no-restore -o ${{ github.workspace }}/packages

    # Upload NuGet packages to github artefacts
    - name: Upload .[s]nupkg packages
      uses: actions/upload-artifact@v3
      with:
        name: DMediatR
        path: ${{ github.workspace }}/packages/*.*nupkg
        retention-days: 10
